_base_: "./PaddleSeg/configs/pspnet/pspnet_resnet50_os8_cityscapes_1024x512_80k.yml"


batch_size: 4
iters: 10000


train_dataset:
  dataset_root: ../old
  train_path: ../old/train.txt
  type: Dataset
  num_classes: 2
  mode: train
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: Normalize


val_dataset:
  type: Dataset
  dataset_root: ../old
  val_path: ../old/val.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
