# normal pc training config
_base_: "./PaddleSeg/configs/pspnet/pspnet_resnet50_os8_cityscapes_1024x512_80k.yml"


batch_size: 4
iters: 500

train_dataset:
  dataset_root: /home/xz/Dev/Grape-Cluster-Closure/dataset
  train_path: /home/xz/Dev/Grape-Cluster-Closure/dataset/train.txt
  type: Dataset
  num_classes: 2
  mode: train
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: Normalize


val_dataset:
  type: Dataset
  dataset_root: /home/xz/Dev/Grape-Cluster-Closure/dataset
  val_path: /home/xz/Dev/Grape-Cluster-Closure/dataset/val.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
